### ISSUE TITLE
Add Creality Ender 5 as an additional option

### ISSUE THREAD

**Issue by JoeMakerDude** [bambulab/BambuStudio#1093]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SaltWei** [comment]
We don't have this printer. It would be great if you can share presets for Creality Ender 5.

**Comment by SaltWei** [comment]
And we can add the presets into Bambu Studio

**Comment by coolshrimp** [comment]
I came here to ask/offer I have multiple Ender 5 Plus that iv been creating a config file for and testing i can share it to be included, i use octoprint and was going to request another feature, since we can send a print to octopi API and it works great it would be nice to be able to view and control the printer in the device tab.

**Comment by SaltWei** [comment]
Included in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53
![image](https://github.com/bambulab/BambuStudio/assets/110660407/8867e09a-3242-4b06-887a-35d6138eb38b)

The initial preset is from OrcaSlicer. Thanks!
