### ISSUE TITLE
New Extrusion Calibration doesnt show Filamentlist

### ISSUE THREAD

**Issue by Marow** [bambulab/BambuStudio#1128]
I downloaded the newest Firmware on my P1P and also Bambu Studio.

I also tried to reinstall it completely and also connected the printer completely again.

I just see this
![image](https://user-images.githubusercontent.com/2269012/213700922-5e348a0d-5f29-4047-a60f-7e6c35dae5c3.png)

I cannot choose any Filament, so i dont get any numbers at the bottom 3 boxes and cannot calibrate :/

**Comment by KD7LRJ** [comment]
I do have filament options in my dropdown, but once I select one, I cannot change the values for the three settings. 

As I understand the text, the filament dropdown should just prepopulate those three items with default values for the selected filament type as a starting place. In my case, I chose "Generic PETG @BBL P1P" which gave me values that are close to what I'm using for Overture PETG (255C, 80C and 10.00mm3).

However, now I am stuck as well because I can't change the values manually. I can put my cursor in the boxes and highlight the numbers, but I can't change them. I want to use 8.0mm3 as my volumetric speed, but am unable to make any changes.

Running the calibration with the default numbers showed that I needed a K=0.060 instead of the default K=0.020. This seems to be helping so far (the first layers of a print I do often looks much better than before).

**Comment by d3s0l3t0r** [comment]
Same here.  No filament selection and no option to enter values ​​manually

**Comment by role79** [comment]
Same here. No filament selection and no option to enter values ​​manually.

**Comment by linx25** [comment]
Same here - no Filament list. Have no AMS connected.

**Comment by linx25** [comment]
It seems there is a Language bug - you have to switch to the english GUI
ctrl + P

**Comment by Marow** [comment]
> 

True! Thats it!

**Comment by d3s0l3t0r** [comment]
Yep.. Changing to english solved the problem

**Comment by lanewei120** [comment]
thanks for reporting this issue

we have fixed it in local , and it will be ready in next version

currently please switch to English for calibration if needed,
and switch back, then input the k value got from calibration in English

Sorry for the inconvenience

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
