### ISSUE TITLE
Purge tower weight

### ISSUE THREAD

**Issue by OmiCron07** [bambulab/BambuStudio#1167]
The purge tower weight is not included anywhere, not even in the print cost. The statistic should indicate the purge weight, either in the flushed filaments or separately.

Left with purge tower / Right without
![image](https://user-images.githubusercontent.com/31325575/214353421-e51f2aea-7246-4bb7-b295-851bfe0ac164.png)

**Comment by MadMax389** [comment]
Interesting. For me, the flushed weight stays the same and it appears the tower is included in the model weight. I always thought the printer would flush into the prime tower so that the flushed volume stays the same, just that some of the flush wound up in the tower. Doesn't seem to be the case in either example.
![image](https://user-images.githubusercontent.com/96731892/214732839-8326546c-7e31-4bcd-b750-c1f364de07f9.png)

**Comment by SaltWei** [comment]
@XunZhangBambu Please move the wipe tower filament consumption from  model to flushed. Now it's calculated into model. This is wrong.

**Comment by XunZhangBambu** [comment]
In 1.8 beta , wipe tower filament consumption has been seperated fropm model .
![image](https://github.com/bambulab/BambuStudio/assets/139755545/9215b236-e118-4d3d-a29f-8302ed41869d)
