### ISSUE TITLE
Renaming the file when "sending to printer SD card" does not work. 

### ISSUE THREAD

**Issue by threepoint2** [bambulab/BambuStudio#1183]
**Describe the bug**
Renaming the file when "sending to printer SD card" does not work. The file is sent with the project name and not the edited name

**3mf File for This Bug**
Not related to 3mf

**To Reproduce**
1. Slice file
2. Send plate
3. On the "Send to Printer SD card screen" click the pencil icon to change the name of the file
4. Click send.

**Expected behavior**
When viewing the file on the printer, it should have the changed name but it still has the original project name/file name.

**Screenshots**
This doesn't need a screen shot. The file name chosen on the Send to Printer SD card screen does not work.

**Desktop (please complete the following information):**
Windows 11
BS 1.4.2.13

**Comment by threepoint2** [comment]
Solved.

**Comment by Guilouz** [comment]
@threepoint2 How do you fix that ? I have same issue.

**Comment by aliasmeum** [comment]
I am afraid this is not solved, and that it is more serious than the “Rename file while sending” function not working. When using 3mf-files from Fusion360 it seems the name of the original part in Fusion360 is stuck no matter what you call the file. When you change filename, or change something in a project, and then send it to the printer you have no way of knowing what file is actually on the SD-card because it names the file the same as before the change. This behavior leaves the “Send to printer” function untrustworthy and thereby useless in the current state. I am really happy that Bambulab added this functionality, since the “Send to printer” function is excellent to use for files that are printed repeatedly, and I hope they fix this as soon as possible.

This is what I have done to try to reproduce the issue.

Fusion360:
-Save “A v1” as mesh in Fusion > “A.3mf”
-Save “B v2” as mesh in Fusion > “B.3mf”

Windows10 File explorer:
-Rename file “A.3mf” > “A-Fusion.3mf”
-Rename file “B.3mf” > “B-Fusion.3mf”

Bambu Studio 1.4.2.13:
-New project
-Add > “A-Fusion.3mf”
-Save project as > “A-Studio.3mf”
-Slice
-Send
Result: File sent to printer is named “A v1”

![20230222_113820](https://user-images.githubusercontent.com/31860542/220615101-154d2a4d-710a-4e37-82a4-c7821e482059.jpg)

![20230222_113832](https://user-images.githubusercontent.com/31860542/220615162-42b2bac3-9725-45ff-adee-5919ba4f0982.jpg)

![20230222_113853](https://user-images.githubusercontent.com/31860542/220615199-7e3e4930-2984-4f16-9a09-76db442ccedb.jpg)

-New project
-Add > “B-Fusion.3mf”
-Save project as > “B-Studio.3mf”
-Slice
-Send
Result: File sent to printer is named “B v2”

![20230222_114042](https://user-images.githubusercontent.com/31860542/220615755-cd602f3b-ab8a-4f1e-a820-705d41b82056.jpg)

![20230222_114054](https://user-images.githubusercontent.com/31860542/220615801-1df59e5e-76d2-4875-9713-c72b384a7914.jpg)

![20230222_114104](https://user-images.githubusercontent.com/31860542/220615842-dbb6f79c-cca1-4c88-8a2a-14d04149bc18.jpg)

-Open project > “A-Studio.3mf”
-Delete “A-Fusion.3mf”
-Add “B-Fusion.3mf”
-Save project as > “AtoB-Studio.3mf”
-Slice
-Send
Result: File sent to printer is named “B v2”

![20230222_114619](https://user-images.githubusercontent.com/31860542/220617029-47b73af1-1467-4819-b630-285491b370c4.jpg)

![20230222_114820](https://user-images.githubusercontent.com/31860542/220616524-8c33adf7-3ea7-4b83-bf1b-02372e2de5b3.jpg)

![20230222_114831](https://user-images.githubusercontent.com/31860542/220616553-fb7fd586-5d71-4470-ab2f-5eb8e6749a5e.jpg)

![20230222_114846](https://user-images.githubusercontent.com/31860542/220616151-9fd9d0fc-bf8d-40e3-aa0e-eca7596aaedc.jpg)

**Comment by lestie198** [comment]
I am still having this issue in 2.1.0.59 on Windows 11.
