### ISSUE TITLE
Cancel a failed print object on a plate when printing object with multiple part or multiple objects.

### ISSUE THREAD

**Issue by The-algar** [bambulab/BambuStudio#1244]
**Cancel a failed print object on a plate when printing object with multiple part or multiple objects.**
I miss the ability to cancel ONE specific object on a plate when printing object with multiple part or multiple objects.
Sometimes a part will detach from the plate and I want to be able to tell the printer to ignore that part but print everything else, so that I don't have to throw away what has been printed so far because a failed part caused an issue. 
Currently, the printer will just continue to extrude when there's nothing underneath it (because the object was detached from the plate during a print) and that will cause spaghetti that I have to manually remove if I want to finsih the print of the other parts/object.

**Comment by jasoncouture** [comment]
This would be awesome when the toolhead knocks over 1 of 30 objects. We could do an online delete of the print, and avoid the spaghetti, as you stated!

Upvote: :+1:

**Comment by j0nas** [comment]
This feature would be _immensely_ appreciated. OctoPrint has a [Cancel Object](https://plugins.octoprint.org/plugins/cancelobject/) plugin that is a must-have when printing multiple objects, perhaps one could draw inspiration from it?

As I am typing this: 
![image](https://user-images.githubusercontent.com/6001131/235628091-e58be9fd-abb1-430e-a1f2-96d663f3150d.png)

**Comment by Fredyy90** [comment]
any updates on this feature? could really use it rightnow, to cancel 1 of 4 object on the bed.

![image](https://github.com/bambulab/BambuStudio/assets/1572327/51372876-78ff-47e4-bb99-61953f4ed983)

**Comment by SaltWei** [comment]
The firmware is under beta test. And will be published soon

**Comment by SaltWei** [comment]
This feature has been included in latest V01.06.00.00 X1 series firmware and [v01.07.01.62 studio](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.01.62). And please make sure both firmware and studio is updated.

Currently it only work in one filament per plate situation, and doesn't support multi filament because of the complexity of flushing and changing filament. One filament per plate situation can still benefit a lot when has some objects failed to be printed and need to be skipped.

Thank you every one for this good suggestion!
