### ISSUE TITLE
Gcode Viewer & Exclude Object

### ISSUE THREAD

**Issue by BloodGuan** [bambulab/BambuStudio#1283]
We need a Gcode Viewer and Exclude Object support to exclude an object from our current print when AI detected a print failure。
AI can detect printing failure, but it can only stop printing, which is not "intelligent". I hope that when the AI reminds me of a failure, I can use the camera to see which part is wrong, then exclude it, and continue printing. Simply stopping printing doesn't help me much. Sometimes I print for 30 hours, and it will be over soon, but because a small part falls off the bed, all the parts have to be scrapped, which will waste a lot.

我们需要一个Gcode Viewer和排除对象的功能，可以在AI检测到炒面的时候，排除掉失败的那部分。
现在AI能检测到炒面，但是只能停止打印，这和你们宣传的“智能”差距很大。我希望在AI提醒我炒面的时候，我可以通过相机看看具体是哪部分出问题了，然后屏蔽掉那部分，然后继续打印。简单的停止打印并没有什么用，有的时候我打印了30个小时，马上就要结束了，但是因为一个小零件脱床，却要把所有的零件全部废弃掉，这也会浪费很多。

fluidd有现成的功能，如下：
fluidd has ready-made functions：

![image](https://user-images.githubusercontent.com/17022345/218625156-a9f8a205-a3f5-4bf6-ace2-fc3b048c8a7f.png)

**Comment by SaltWei** [comment]
This feature has been included in latest V01.06.00.00 X1 series firmware and [v01.07.01.62 studio](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.01.62). And please make sure both firmware and studio is updated.

Currently it only work in one filament per plate situation, and doesn't support multi filament because of the complexity of flushing and changing filament. One filament per plate situation can still benefit a lot when has some objects failed to be printed and need to be skipped.

Thank you every one for this good suggestion!
