### ISSUE TITLE
Enable or disable dark mode checkbox on macOS

### ISSUE THREAD

**Issue by suchabadperson** [bambulab/BambuStudio#1357]
This option exists in Bambu Slicer for Windows, but is not present in the macOS version and would be very useful.

**Comment by walterwongbbl** [comment]
Hi.
Studio's dark mode will follow the system settings of macos. 
modify appearance setting, and studio will follow the system to switch dark mode.
![img_v2_2df969ba-a16d-404d-b8c9-b8b202ce3f6g](https://user-images.githubusercontent.com/120699126/222305355-a25d01ba-8537-4dd0-bf90-8b81040f0da6.jpg)

**Comment by suchabadperson** [comment]
Yes, but I find it very useful to be able to switch to  dark mode only within the application, keeping the light theme on macOS.

**Comment by keithel** [comment]
This issue also applies to the Linux release of Bambu Studio (AppImage, tested on Ubuntu 23.04 Lunar Lobster). Dark/Light mode is only configurable in the Gnome system configuration dialog. I'd like the ability to switch from dark mode to light mode just within Bambu Studio.

The reason I need this is to work around another bug, which I came here to report - while searching to see if anyone had reported it yet. That bug is that the text color of properties in the "Object" (per-object) pane is extremely illegibile - the color is a grey color that is only barely different from the dark mode background grey. I'll report this separately.

**Comment by suchabadperson** [comment]
It does not seem that they will ever implement this idea as it exists in other applications. Unfortunately there is no other way to enable it in macOS than switching everything to dark mode.

**Comment by keithel** [comment]
@walterwongbbl Did you close this because it's now implemented (enabling/disabling dark mode within app/decoupled from window manager setting)? 
I thought I saw an issue go by that was the same as this marked done...

**Comment by suchabadperson** [comment]
Any update on this? @walterwongbbl

**Comment by packhamc** [comment]
Any news on dark mode for Linux?

**Comment by xXPerditorXx** [comment]
Still no update on this...
