### ISSUE TITLE
Add Pause icons are difficult to see due to size and color

### ISSUE THREAD

**Issue by moop2000** [bambulab/BambuStudio#1387]
"Add Pause" icons are difficult to see due to size and color in the preview screen.

The icons need to be larger, and different in color so as to easily stand out against the background color.

**Screenshots**
Example of icons in question.
![image](https://user-images.githubusercontent.com/19175728/222561476-f3c8234a-2d5b-4f19-89ae-bc0fb54657b8.png)

Example of difficulty seeing icon on a full screen. It is half way up the layer indicator.
![image](https://user-images.githubusercontent.com/19175728/222562647-ad52562f-2fe6-43d4-a2e6-bb8eee657045.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - Screen: 3840x2400, Scale: 200

**Comment by LiZ-Li-BBL** [comment]
Thanks for your suggestion, a new icon design will be applied in the future.

**Comment by LiZ-Li-BBL** [comment]
We noticed that the scroll bar and thumbnail in your preview page are not in the right scale. This is because your screen resolution is too high. You can temporarily turn the screen scale down to 100% to get a normal size of preview items. We will add the adaptation for high resolution screen in the near future.

**Comment by LiZ-Li-BBL** [comment]
We added a more visible mark beside the tick.
