### ISSUE TITLE
AMS filament backup not working on P1P

### ISSUE THREAD

**Issue by Shareisfun** [bambulab/BambuStudio#1444]
P1P OTA version01.02.01.00（20230302）

Has anybody got AMS filament backup working?

I havent, and i have to log the printer out of the slicer and back in to enable it but i isent working and i’m using beta slicer? When i close the slicer i have to log the printer out and back again to be able to choose it, but it not working`

[Picture of AMS](https://scontent-cph2-1.xx.fbcdn.net/v/t39.30808-6/334712680_150109854592214_7354183288760062298_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5cd70e&_nc_ohc=SH99wYAL-cYAX_00lIF&_nc_ht=scontent-cph2-1.xx&oh=00_AfBPhyp8Ocx7dZEgUOSEeX0hlEVscgrB1vri3Mn4OG4Zkg&oe=640E269C)

edit: Now i’m on version 1.5.0.60 as off to day but still not working.

**Comment by ab3dgeek** [comment]
it worked for me just a few hours ago.

bambu studio 1.5.0.60
p1p fw: 01.02.02.00
ams fw: 00.00.05.96

**Comment by Shareisfun** [comment]
I have the same setup and it is not working for me?
[Video](https://drive.google.com/file/d/16UveoT8CL7HrIEkN54nrcdrZkqbWyo7z/view?usp=sharing)

**Comment by walterwongbbl** [comment]
![image](https://user-images.githubusercontent.com/120699126/225222743-7879ce14-7aa4-45e0-8a19-04c0d578f2a4.png)
![image](https://user-images.githubusercontent.com/120699126/225222771-7d10e911-3aa5-4132-bb0d-2695129953c4.png)

Hi, Because you are currently selecting a virtual tray.  
you can select AMS tray and try again

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
