### ISSUE TITLE
[v1.6.0 Public Beta BUG] Advanced cut with connectors doesn't work

### ISSUE THREAD

**Issue by moebis** [bambulab/BambuStudio#1633]
Just did a default slice to a cube primitive, added 3 pegs and printed using the default 0.20mm Strong profile, with Bambu PLA. Either the pegs are too large or the holes are too small. No amount of force could mash them together, see image:

[https://imgur.com/a/wXmwv0o](https://imgur.com/a/wXmwv0o)

**Comment by Hologos** [comment]
In my experience, holes get smaller due to shrinkage as a filament cools down. You either have to scale the pegs down or use `Quality > Precision > X-Y hole compensation` but it can make other holes too big. So I'd scaled the pegs down at least 0.15mm in diameter. Or use sand paper :-)

The same happens in Prusa Slicer AFAIK.

**Comment by zhimin-zeng-bambulab** [comment]
@moebis 
Due to thermal expansion and contraction of the material, some printing mistake may occur, you can set the size tolerance to 5%, or adjust this value according to your printing situation.

**Comment by moebis** [comment]
I'm using Bambu filament (matte PLA), I thought it would have been calibrated for that. Ok I'll do some more testing. Thanks.

**Comment by Hologos** [comment]
No filament profile can be calibrated for shinkage. Circular holes experience more shrinkage that other shapes.

**Comment by moebis** [comment]
> No filament profile can be calibrated for shinkage. Circular holes experience more shrinkage that other shapes.

lol, isn't that exactly what you have to do (calibrate) by printing and adjusting yourself? That's called calibration. Material properties don't change (much). If Bambu did testing on their PLA, they would know at known temps/speeds their PLA shrinks x% factor by hole size. I don't think is an impossible ask.

**Comment by Hologos** [comment]
> > No filament profile can be calibrated for shinkage. Circular holes experience more shrinkage that other shapes.
> 
> lol, isn't that exactly what you have to do (calibrate) by printing and adjusting yourself? That's called calibration. Material properties don't change (much). If Bambu did testing on their PLA, they would know at known temps/speeds their PLA shrinks x% factor by hole size. I don't think is an impossible ask.

The shrinkage is more prevalent with smaller holes rather than with larger ones. It also depends on a temperature that you print at. And I don't mean the temperature you see on the printer but the actual temperature of the filament when it exits the nozzle. When you print fast, a filament doesn't have enough time to heat up to the temperature of a heatblock. The slicer slows the printhead down for some features, it has to adhere to minimum layer time and few other variables so you don't really know the exact temperature (and believe me, it can very up to 20 degrees). There is so much variables that it's easier to make the hole bigger when designing rather than settings a single value. You'd still have to have few profiles with different value depending on size of a hole.

**Comment by zhimin-zeng-bambulab** [comment]
We change the tolerance to absolute value form, the unit is mm, generally set  size tolerance to 0.1-0.2mm under the request, which can make the cutting parts fit better.
