### ISSUE TITLE
Exclude objects while printing

### ISSUE THREAD

**Issue by Gil80** [bambulab/BambuStudio#1739]
**Is your feature request related to a problem? Please describe.**
Having to cancel a really long print that has multiple objects, only because one object failed. This is causing a huge loss of filament, time, electricity, money and frustration.

**Describe the solution you'd like**
Like klipper and octoprint, allow to cancel a failed object on the build plate, instead of cancelling the entire print.

**Describe alternatives you've considered**
Using printers that support Klipper or Octoprint "Cancel Object" feature.

**Additional context**
https://www.klipper3d.org/Exclude_Object.html

**Comment by SaltWei** [comment]
This feature has been included in latest V01.06.00.00 X1 series firmware and [v01.07.01.62 studio](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.01.62). And please make sure both firmware and studio is updated.

Currently it only work in one filament per plate situation, and doesn't support multi filament because of the complexity of flushing and changing filament. One filament per plate situation can still benefit a lot when has some objects failed to be printed and need to be skipped.

Thank you every one for this good suggestion!
