### ISSUE TITLE
[Feature Request] Per Object Settings as used in Prusaslicer

### ISSUE THREAD

**Issue by GuyH77** [bambulab/BambuStudio#176]
Please look to implement the per object print options. It provides so much control over a print. The quality of prints can be greatly improved using these options.

![image](https://user-images.githubusercontent.com/106596720/187068475-a4bb80f6-a161-4dd5-bfde-ab70c20e0a4d.png)

**Comment by RobinWhitfield** [comment]
This already exists. You can adjust settings for each object individually, and if your models are small enough, you can also print by object rather than by layer, which gives all sorts of options around having different models with totally different layer heights.

![image](https://user-images.githubusercontent.com/63362209/187071125-2ce673d8-6251-441b-9569-57e91f65f197.png)
