### ISSUE TITLE
Overhangs Not Detected when Support Z Distance is 0

### ISSUE THREAD

**Issue by djngnear** [bambulab/BambuStudio#1774]
**Describe the bug**

Setting the Top Z Distance to 0 in order to use support interface filaments makes the slicer ignore the overhangs therefore the printer won't slow down for them. Setting the Top Z Distance to anything above 0 makes the overhangs detectable again.

**To Reproduce**

1. Go to Support Tab
2. Click on Top Z Distance and set to 0
3. See error in slice preview of model with overhangs.

**Expected behavior**

The overhangs should be detected in the slice preview.

**Screenshots**

![BS Overhang Issue Pic 1](https://user-images.githubusercontent.com/87901234/236709404-8039c1ea-2b36-4ab2-b543-da3d074512fb.JPG)
![BS Overhang Issue Pic 2](https://user-images.githubusercontent.com/87901234/236709407-4990fb5e-c188-4a51-a1e7-2ff041ca03d5.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] Windows 10

**Comment by tangketan** [comment]
Please share the 3mf so I can check the problem. Thanks~

**Comment by djngnear** [comment]
> Please share the 3mf so I can check the problem. Thanks~

https://drive.google.com/file/d/1NMJYv5DDirrNsJYdhf1VhGcfJvOwEec0/view?usp=sharing

**Comment by tangketan** [comment]
I see. If speed is what you care, actually it's fine. You can check the speed profile, the speed of the overhang perimenters are actually lowered down.
![image](https://github.com/bambulab/BambuStudio/assets/13730459/cc7bb9e0-6734-4f06-a82b-7bce7862baad)

I guess what confuses you is the displayed perimeter type. The overhang perimenters are not classified as "overhang wall" when top z distance=0. This issue is related to #1464 . The perimeter type depends on the support type. But it's OK in your case. The speed calculation is not affected by the detected perimeter type.
