### ISSUE TITLE
Plate names do not show in plate lists

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1781]
**Describe the bug**

In the objects list plates are shown as "Plate n" where n is the plate number. 
In the plates sidebar when in preview mode, only the plate number is shown.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**
When a plate has a name, and it always has at least the default name of "Untitled n", the name should be shown instead of the number. It is much easier to find the correct plate to make a change or print it using the name.

Even better, if a plate has not been given a name other than the default and a single object is placed on the plate, then use the object name as the default name for the plate.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows]
 - Version 1.6.2.4

**Comment by Haidiye00** [comment]
Can you provide pictures

**Comment by julie777** [comment]
@Haidiye00 
As you can see, neither the plates in the object list or the plates in the sidebar are showing the names that I have given them.

![image](https://github.com/bambulab/BambuStudio/assets/5090005/7f6914e2-5f99-4724-96e9-8c4a9893e3e4)

**Comment by Haidiye00** [comment]
![img_v2_065efb66-97c1-4e15-9090-a533076b67cg](https://github.com/bambulab/BambuStudio/assets/132528822/16de55c8-aa83-4e0a-83b9-e48f8ff51d68)

This feature is currently almost developed, and the effect image is as shown above. Due to the small space, adding a name to the disk thumbnail is not considered. Still undergoing internal testing and not yet contracted. Please wait for the new version of the software. May I ask if there are any additions to the rendering? Thank you
