### ISSUE TITLE
Generic TPU Settings

### ISSUE THREAD

**Issue by Grzegorz66** [bambulab/BambuStudio#1802]
question about BambuStudio and settings for generic TPU?
Bambu settings for TPU are 240° for the nozzle and 45° for the heated bed.
The generic TPU producer (Jayo) says 185° to 215° for the nozzle and bed heat not necessary.
I use on P1P the textured plate.
My question is, should I stick to the manufacturer's specifications/settings or better to BambuStudio specifications/settings?
Thanks for help.

**Comment by QingZhangBambu** [comment]
Firstly, before you use TPU， you are suggested to put it in a forced air oven at 75 ℃ for 8 hours to dry it, or use Bambu X1C printer's heatbed to dry it (please visit this website to get more details: https://wiki.bambulab.com/en/general/bambu-filament-drying-cove). After that, put the filament in a sealed box with desiccant to prevent it from absorbing moisture again while you use it.
   Secondly, the recommended nozzle and bed temperatures may differ from filament brands and printer types. To make sure that most brands‘ TPU stick to the plate firmly, we set a higher bed temp for Generic TPU. And as for nozzle temperature, you can try a little model first at 225 ℃ which is almost the middle value of 215 and 240 ℃; if it turns out that it is overheated and overflows, you can set a lower temp, and set a higher one on the contrary.
   May you have a pleasing experience.
