### ISSUE TITLE
Steam OS(Arch Linux) support

### ISSUE THREAD

**Issue by hogum** [bambulab/BambuStudio#2827]
Hopefully support for steam os will be added so we can do slicing on the steam deck :)

**Comment by Schokobecher** [comment]
Without owning a SteamOS device:
What is the issue with the AppImage? Or even one of the available AUR packages?

**Comment by lanewei120** [comment]
how about run the appImage of ubuntu on steam OS?
it can be run well on arch linux before after install some libraries such as  webkit2gtk

**Comment by Schokobecher** [comment]
@lanewei120 the point of an AppImage is to bundle all required libs, that would include _webkit2gtk_
Some GNOME-based distros come with it pre-installed, but not that shouldn't be what is relied on, otherwise providing a DEB/RPM etc. would make more sense as it can load the required dependencies by itself.

**Comment by hogum** [comment]
> @lanewei120 the point of an AppImage is to bundle all required libs, that would include _webkit2gtk_ Some GNOME-based distros come with it pre-installed, but not that shouldn't be what is relied on, otherwise providing a DEB/RPM etc. would make more sense as it can load the required dependencies by itself.

Agree. On steam os, using pacman to install software is very troublesome. If the software package requires dependencies, it is easier to use Flatpak.
