### ISSUE TITLE
Coloring not working on components

### ISSUE THREAD

**Issue by Tomzrk** [bambulab/BambuStudio#3213]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

window 11

### Additional system information

Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
12.0 GB  RAM

### Printer

bambu lab p1s

### How to reproduce

I designed the part on fusion 360 and exported the file stp , opened it on bambu studio and tried coloring some components but after slicing the part only the body show up without the colored components
![1](https://github.com/bambulab/BambuStudio/assets/113375679/8dea9cec-d62b-455e-88fc-31647fec56e2)

### Actual results

![2](https://github.com/bambulab/BambuStudio/assets/113375679/ce4abce5-8e16-4a8f-9317-d427c39c4323)
only body show up without components

### Expected results

i done the same thing on different part and it worked fine 

### Project file & Debug log uploads

[xbox cont bug.zip](https://github.com/bambulab/BambuStudio/files/13760591/xbox.cont.bug.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/84925b2e-65d0-42dc-8625-9f549e25a8dd)
Because the Object of this model contains multiple components, and there is overlap between the components. In the overlapping part, one color is 1 and the other is 4. When two colors overlap, we give priority to displaying the color with the smaller number. So if you want to show the desired effect, you can add a new material 5 and use material 5 to color the bottom surface, as shown in the picture.

**Comment by Tomzrk** [comment]
How can I print it that way ?

**Comment by zhimin-zeng-bambulab** [comment]
You can create a new filament 5, and then repaint all the colors of the original filament 1 with filament 5. Then when sending for printing, just map filament 5 to the corresponding ams slot.

**Comment by zhimin-zeng-bambulab** [comment]
@Tomzrk  Did the above method solve your problem?

**Comment by Tomzrk** [comment]
No it didn't

**Comment by zhimin-zeng-bambulab** [comment]
@Tomzrk  After you add a new filament 5, the bottom surface still only has one color after slicing?
![image](https://github.com/bambulab/BambuStudio/assets/120697589/269ff7f6-7754-433a-866a-705973375e86)

**Comment by zhimin-zeng-bambulab** [comment]
@Tomzrk  Could you please tell us what problems currently exist with the above method?
