### ISSUE TITLE
Display Bambu Studio Version Name In Device Update Page

### ISSUE THREAD

**Issue by ThePieMonster** [bambulab/BambuStudio#3465]
The version number is not present or to difficult to find.

The version of Bambu Studio should be listed here:

<img width="1914" alt="image" src="https://github.com/bambulab/BambuStudio/assets/11359134/c5b4ff29-7d04-4912-bade-d02125afcc66">

**Comment by LJKraus** [comment]
The Studio software is independent of the hardware.

Firmware version is on the Device page because it is a part of the hardware.

The standard location to find the software version of most programs is Help>About
![image](https://github.com/bambulab/BambuStudio/assets/139707784/69dfa416-83ff-45ba-96e3-876671b515ff)

**Comment by ThePieMonster** [comment]
I agree. 
I noticed when going from 1.7 to 1.8 I have a help option under file where as before I did not.
