### ISSUE TITLE
调整了可变层高的层支持界面材料不正确

### ISSUE THREAD

**Issue by yueduz** [bambulab/BambuStudio#3931]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Built from source by yourself or others

### OS version

archlinux

### Printer

Bambu A1

### How to reproduce

调整可变层高,调整的层需要包含有支持界面的层.

### Actual results

支撑界面使用了主体的材料

### Expected results

使用支撑材料打印支撑界面

### Project file & Debug log uploads

[外壳下.3mf.zip](https://github.com/bambulab/BambuStudio/files/15075584/3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by XunZhangBambu** [comment]
@yueduz 
Sorry, I didn't find any cases where the support interface was printed using the support body filament. In order to clearly distinguish between the support and the model, I added a new filament and used it to print the support body, but still did not find any abnormalities."

![image](https://github.com/bambulab/BambuStudio/assets/139755545/4cc54439-d605-48b0-a2a3-cb544b7f3035)

![image](https://github.com/bambulab/BambuStudio/assets/139755545/249424db-79cf-4242-b3ac-ef1822f9e1cc)
