### ISSUE TITLE
3MF files exported from Bambu Studio are not made to specification

### ISSUE THREAD

**Issue by gjarnos** [bambulab/BambuStudio#4292]
### Bambu Studio Version

1.9.2

### Where is the application from?

Bambu Lab Official website

### OS version

All

### Printer

Not applicable

### How to reproduce

Export a 3MF

### Actual results

3MF files exported from Bambu Studio are not made to specification 

### Expected results

I've noticed `paint_color` is not part of the 3MF specification although it is in the 3MF's exported from Bambu Studio only. Can the team at Bambu please outline all of the different ways that Bambu has diverged from the 3MF specification so that proper parsers can be developed. Thank you.

### Project file & Debug log uploads

Not Applicable

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
the 3mf exported from Bambu Studio are made to specification
the 'paint_color' is just "other attrubute"
![image](https://github.com/bambulab/BambuStudio/assets/106916061/788ae05c-2a7a-4e88-86a2-d387a6431de7)

you can skip it

for Bambu's 3mf, you can refer to https://wiki.bambulab.com/en/software/bambu-studio/3mf-compatibility for the details

if you want to parse this 3mf, you can just refer to the codes in bambustudio

**Comment by gjarnos** [comment]
Hi @lanewei120. Thank you for responding. I have another question regarding `paint_color`. Why not use the base material or color group which is fully supported by lib3mf?

**Comment by lanewei120** [comment]
that color is used for the original trangles or group
our paint_color is derived from prusa slicer, which can be  used for the triangles splitted from the original

**Comment by gjarnos** [comment]
When you say it's derived from Prusa Slicer, are you saying they use `paint_color`?

**Comment by lanewei120** [comment]
they use a different name
![image](https://github.com/bambulab/BambuStudio/assets/106916061/8d870dcb-cb4d-4aed-af0e-6b3baa418af6)

**Comment by lanewei120** [comment]
not a issue,  close it

**Comment by t-paul** [comment]
My reading of that part of the specification

> Within this core XSD schema (see Appendix B.1. 3MF XSD Schema), extension points have been explicitly entered in the
form of <any> elements and <anyAttribute> (also visible in the element diagrams further along in this specification). These
are required to come from other namespaces, which SHOULD point to a way to find the appropriate specification and
accompanying XSD schema.
> Vendors MIGHT define private 3MF extensions. The specifications of private namespaces (i.e. that are not ratified by the
3MF Consortium) need to be negotiated between parties in the ecosystem.

is that the naming shown in https://github.com/bambulab/BambuStudio/issues/4292#issuecomment-2172079128 is spec compliant as it's using a separate namespace. Only using `paint_color` from the core namespace seems to violate the requirement given in that paragraph.

I'm just noting that while implementing the color import for OpenSCAD. We will not be able to support that kind of coloring as we use the official 3MF library which seems to have no means of reading non-spec data (at least in library version v1, will be looking at v2 next).

It would be great finding a solution that is covered by official specification.

**Comment by t-paul** [comment]
https://github.com/prusa3d/PrusaSlicer/issues/12502#issuecomment-2037338782 seems to agree with my earlier statement.

Current state now is:
* Multiple slicers use different attributes, but each needs to try reading the others too
* BambuStudio uses a non-spec compliant one, PrusaSlicer uses a technically spec compliant one (using different namespace)
* None of the ways are supported by the official 3MF library

I would not call this a good and future proof solution. Anyone who has contacts to the 3MF foundation to find an official and unified way of specifying this information?

**Comment by t-paul** [comment]
> As a potential option, if you can get the lib3MF data out of the prusa or Bambu files

That is exactly the problem. The official [3mf library](https://github.com/3MFConsortium/lib3mf), even in the latest version has no means to access that data at all (see also your own still unanswered question https://github.com/3MFConsortium/lib3mf/issues/377).

OpenSCAD is a very small projects in regard of development power, It's not feasible to add and maintain a custom XML parser where a fully supported and officially maintained library exists (especially with the very much non-trivial internal structure of 3MF files).

**Comment by FastFrench** [comment]
I've noticed that current OrcaSlicer handles colors a different way in .3mf files. 
This line in the xml models let me think that this behavious is or was somewhat related to bambulab
![Image](https://github.com/user-attachments/assets/f4a18414-3350-4c79-8f0a-c658a2bd8fc5)

Even when the model is colorized (by filaments assignments), the colors do not appear in any way:
![Image](https://github.com/user-attachments/assets/4e6a6760-2596-4c45-9914-ca71da4ed170)

And here in fact, the color information only relies on metadata, where an extruder is associated to each object, and then a color defined to each extruder/ 
![Image](https://github.com/user-attachments/assets/df86990a-334c-4bf9-bd2b-aedc29ebf17b)
(in model_settings.config)

![Image](https://github.com/user-attachments/assets/9f399513-329e-41bc-a352-3d00773f1828)
(in project_settings.config)

This is quite an ugly way to code colors, isn't it?
Does or did Bambu Studio sometimes code colors that way?

**Comment by t-paul** [comment]
Well, we are talking on a closed issue here, so it's a bit like people shouting at clouds. I wonder what the best option is to bring that to some actual attention.

Considering Prusa is member of the 3MF Consortium (or was?, I can't find any reference on the current member page), maybe a new issue there could get things moving?

Ultimaker *is* still listed as member, but I don't know what the state of Cura is in that regard, and if they would be interested in driving some sort of specification effort.

**Comment by amoose136** [comment]
>Considering Prusa is member of the 3MF Consortium (or was?, I can't find any reference on the current member page)

According to https://3mf.io/whoswho/ Ultimaker and Prusa are still members.

> so it's a bit like people shouting at clouds.

Agreed. I do have a rant as long as we're shouting at clouds:

I'm working on building a 3mf spec compliant importer/exporter to Blender via an extension powered by lib3mf. My focus is on doing things in a way that is as compatible with spec as possible but still works with the slicers...but also makes 3mfs whose color information is viewable with tools like three.js (which follows the spec). The fragmentation of 3mf support is certainly a thorn in my side at the moment. IMO the decision use segmentation strings in the first place has outlived its usefulness and within the slicers things should be internally swapped to UV textures going forward. I doubt Bambu, Orca, Ultimaker, or Prusa devs will ever want to do that but textures are a better way of solving the same problem for a variety of reasons:

For example, right now you can't specify a gradual increase in fuzzy paint amount (just on or off) but that would be possible with a grayscale texture driving things under the hood. Similarly, bump maps (part of spec) would allow for adding micro texturing to the surface of models based on a raster image import instead of just svg as we currently have in the slicers.

My only reservation about using images for color information is that images can hold many more colors than most FDM printers can handle which could make importing complex. It would be helpful if 3mf itself explicitly supported using indexed color palettes on images to help handle this. 3mf supports png and jpg for images but only png supports indexed colors and also jpg is lossy.

For now I'm stuck with the prospect of writing a slicer compatibility layer on top of lib3mf that will look at the segmentation strings and bake the contents at import-time to generated textures that can then be edited. On export it gets messy but, alas, that's world we live in. The worst part is that on export you're going to have to pick a "flavor" of 3mf because each slicer does something a little different. It's not even just non compliant 3mf, it's several different non-compliant 3mf variants. How they each work you can only really know by looking at the source code as the documentation for each format variant doesn't exist.

I guess I just wish the vendors would switch to their own propriety ending ( eg. `.orca` / `.prusa` / `.bambu`) instead of making non standard 3mf and acting like it's a bespoke version of 3mf. It's the USB-C problem all over again and it's an interoperability nightmare.
