### ISSUE TITLE
BambuStudio should remember printers that have been attached.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#525]
While working remote had a problem connecting to the device. network showed it was still online and Bambu Handy could talk to it. So elected to remove printer and add back but after removal it did not know about the printer and wanted me to use a QR code again but I'm not onsite and have no physical access to printer. It should remember previous devices that have been attached to and offer them as possible devices.

Also, after removing the printer from Studio it's no longer available in Handy.  The printers last known information should always be available for use and allow it to attempt to connect.  Now I have no choice but wait for the next 12 hours until I can get back to the printer physically and have wasted half a day that I cannot print.

What's the use of having cloud services if things aren't remembered by the cloud.

**Comment by YifanWuBambu** [comment]
By "removing printer", you mean log out from a printer?
![image](https://user-images.githubusercontent.com/110661856/198523725-7f0a500b-8bd8-430d-b2f7-58ba62252afa.png)

If so, the printer no longer belongs to that account in the Cloud service and is considered as a new printer. Thus you cannot see it over internet.

Why did you log out your account from the printer? Try to recover the network connection?

**Comment by YifanWuBambu** [comment]
@randyre 
Unfortunately, logging out/in does not resolve this problem.
We need to find out the root cause of this problem.

Could you reproduce this problem? If so, Could you help provide the log files.
-------------------------------
How to get log files:
![image](https://user-images.githubusercontent.com/110661856/198868268-6a478d51-1c43-41e6-9544-88b1ec1eb9d2.png)
![image](https://user-images.githubusercontent.com/110661856/198868287-3ddbbc24-d7d7-4c75-8476-d14da4aac1c2.png)

**Comment by randyre** [comment]
The problem has not reoccurred, but am having lots of WiFi disconnects with the last firmware and software update. Also, Camera/Video is terribly slow now as of .30
