### ISSUE TITLE
[Bug] Trojan/Emotet.mv

### ISSUE THREAD

**Issue by gofromzero** [bambulab/BambuStudio#56]
![image](https://user-images.githubusercontent.com/30290644/180605663-1d2637cb-cd0e-4b23-a195-01fcb1ad963b.png)
下载网络插件时，会报木马 这是什么情况
version  01.01.00.14 win

**Comment by wuyifanfancy** [comment]
@gofromzero 
What's the security software are you using?
We will check the issue on the same security software.

**Comment by gofromzero** [comment]
火绒安全 win   https://www.huorong.cn/

**Comment by martinfrancois** [comment]
I also noticed on macOS, the "Web Shield" component in "Avast One" anti virus blocks connections to both download the network plug-in and do the login or connection to the printer. I tried adding exclusions for `bambulab.com` and `iotcplatform.com` but this didn't help, I need to turn off the "Web Shield" component in order to be able to use this feature.

**Comment by YifanWuBambu** [comment]
It is the same issue at #149.
![image](https://user-images.githubusercontent.com/110661856/187606334-3943fd77-34f9-4683-913d-c245b3ad6010.png)
