### ISSUE TITLE
[Feature Request] Cancel one object, not entire print

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#656]
i would like to be able to stop one object on the bed if it fails instead of entire print. will help save filament.

**Comment by YifanWuBambu** [comment]
This is in our plan list, but may be not in recent releases.

**Comment by jacycatlin** [comment]
It's the one Octoprint feature I miss the most often, by far.

**Comment by SaltWei** [comment]
This feature has been included in latest V01.06.00.00 X1 series firmware and [v01.07.01.62 studio](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.01.62). And please make sure both firmware and studio is updated.

Currently it only work in one filament per plate situation, and doesn't support multi filament because of the complexity of flushing and changing filament. One filament per plate situation can still benefit a lot when has some objects failed to be printed and need to be skipped.

Thank you everyone for this good suggestion!
