### ISSUE TITLE
[Feature Request] Exclude print region

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#667]
On my previous printer in octoprint, i had a plug in to exclude region on the build plate (link: https://plugins.octoprint.org/plugins/excluderegion/ ) mid pring if someting went wrong with one of the objects you could exclude that region there the object was, which was quite useful not to waste filament on half printed objects that were fine.

**Comment by YifanWuBambu** [comment]
Canceling one or more objects during printing is in our plan. But may be not in recent releases.

**Comment by RidoKilos** [comment]
Yes! Love to see this acknowledged by the team. This will be an amazing addition to the software! 💪

**Comment by SaltWei** [comment]
This feature has been included in latest V01.06.00.00 X1 series firmware and [v01.07.01.62 studio](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.01.62). And please make sure both firmware and studio is updated.

Currently it only work in one filament per plate situation, and doesn't support multi filament because of the complexity of flushing and changing filament. One filament per plate situation can still benefit a lot when has some objects failed to be printed and need to be skipped.

Thank you every one for this good suggestion!
