### ISSUE TITLE
add Z-Offset setting

### ISSUE THREAD

**Issue by Woki-Leo** [bambulab/BambuStudio#674]
My printer consistently makes the first layer too thin.
I have no way of adjusting that. Neither in the printer firmware nor in the Gcode.
Pls fix that.
![grafik](https://user-images.githubusercontent.com/96394750/202868514-859f49f1-ad02-48e6-a1b4-20d5c7b38c62.png)

**Comment by Benderrodrigu3z** [comment]
The Current Fix is to run a Self-Test from the last tab on the left either that sets the Z offset or another thing is Run the Calibration from the 2nd or 3rd tab

I believe that the first one (Self-Test) sets the Z offset though

**Comment by Benderrodrigu3z** [comment]
They said they added this in the new firmware, you have to add it to the start gcodeSincerely,Shane FSent from my iPhone13On Dec 21, 2022, at 2:49 PM, ChaosBlades ***@***.***> wrote:﻿
We need this setting in order to offset PETG first layer. PETG sticks too well and being able to set a Z offset will resolve the issue. Even if it does not damage the bed it is a giant pain to remove the prime/calibration lines without raising the Z offset.

**Comment by suit** [comment]
you can set the z offset in the startup gcode - it is there for the P1P for example for the PEI sheet
