### ISSUE TITLE
[BUG / 01.01.00.14 / macOS] Printable Area locked

### ISSUE THREAD

**Issue by Gio76** [bambulab/BambuStudio#69]
The Z-Height (Printable Area) of the printer profiles is locked to 250mm:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/26906928/180697833-014a8f3a-6db4-48c1-ad43-ea910dea36c2.png">

Is there a specific reason this value is not editable? Also, why is it set to 250 and not to 256 (as per the advertised print area)?

**Comment by RobinWhitfield** [comment]
It's locked so that you can't inadvertantly slice g-code for the printer that is higher than the machine will go. That's absolutely what I'd expect for an inbuilt machine profile - same as the max movement speeds.

Now why it's locked to 250 rather than the advertised 256mm is a very different question...

**Comment by wuyifanfancy** [comment]
We reserved 6mm due to the following reason:
1. z-hop feature
2. prevent uncleaned bottom of chassis

We are considering whether to make this config editable.

**Comment by Gio76** [comment]
Solved in the latest version (v1.1.1.1)
