### ISSUE TITLE
Models don't lay perfectly flat when imported.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#756]
**Describe the bug**
bambuStudio does not properly drop model onto build plate.

**3mf File for This Bug**
Included STL file, Cura's .3mf, and a picture of both side by side in studio sliced.

**Steps to reproduce the behavior:**
1. Import the model and slice with supports (any type of support) when sliced with supports some of the model does not have supports where there should be. This is apparent by the horizontal surface not being perfectly level with the build plate

2. Import the same model into Cura. No need to do anything, just import. Cura places the file on the build plate.

3. Now export that model from Cura and save it as .3mf to get the new orientation of the model.

4. Import .3mf into Studio and studio now does not have to adjust the model as Cura has already done it, and supports are now generated properly.

**Expected behavior**
Should properly level the model on the build plate

**Screenshots**
File on the left is Cura exported, file on the right is STL directly imported into Studio

No rotation was done within either slicer. The problem seems to be Studios' ability to properly lay the model onto the bed,

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bambustudio 01.03.01.01
![Photo Dec 02 2022, 18 25 54](https://user-images.githubusercontent.com/60475095/205413488-55b29e1c-0f5e-4d3c-aaf5-39588b118a85.jpg)
[SkullCandy files.zip](https://github.com/bambulab/BambuStudio/files/10145211/SkullCandy.files.zip)

**Comment by Benderrodrigu3z** [comment]
here's a hint, don't use Cura, or export it from Cura but not as a 3mf and do your edits in the BS Slicer

**Comment by randyre** [comment]
@Benderrodrigu3z 

I didn't use Cura initially, I loaded directly from the STL file. Re-read the bug report and you will see Cura was only a troubleshooting step.  I included the file and if you're curious you're welcome to try it and you'll see what the problem is. 

I used Cura to proof the problem and then used Cura as a workaround to get Studio to properly position the model. For some reason, Studio would incorrectly lay the model on the print bed, but Cura did it right the first time, and after exporting as a 3mf I was able to get Studio to detect iot properly too.

The problem is clearly in Studio and how it detects the flat surfaces of some models.

**Comment by Benderrodrigu3z** [comment]
Good times when you hit unsubscribe and this nucklehead tags you Sincerely,Shane FSent from my iPhone13On Dec 6, 2022, at 12:53 PM, randyre ***@***.***> wrote:﻿
@Benderrodrigu3z
I didn't use Cura initially, I loaded directly from the STL file. Re-read the bug report and you will see Cura was only a troubleshooting step.  I included the file and if you're curious you're welcome to try it and you'll see what the problem is.
I used Cura to proof the problem and then used Cura as a workaround to get Studio to properly position the model. For some reason, Studio would incorrectly lay the model on the print bed, but Cura did it right the first time, and after exporting as a 3mf I was able to get Studio to detect iot properly too.
The problem is clearly in Studio and how it detects the flat surfaces of some models.

**Comment by randyre** [comment]
@Benderrodrigu3z 

Sorry, I had no way to know you unsubscribed, figured you left a comment, you wanted an answer.

Sincerely,  **_this nucklehead_**

**Comment by ResiduaLiu** [comment]
Hi Randyre,
Thanks for reporting this issue. The STL file from Cura has some non-manifold faces. That's why they have different slices and support results. (See the defects caused by non-manifold faces below.)
It should be a support generation bug rather than an orientation problem. After repairing the model from Cura, they have the same results. 
For a quick fix, you can use the support painting tool. Select the third type "fill", then left click on the areas where you want to generate supportst-click on the areas where you want to generate supports. (See the last picture.)
Our team will fix it ASAP.

![image](https://user-images.githubusercontent.com/50384819/206660934-6c199276-d96b-4d2d-8b6c-f53582128b94.png)
![image](https://user-images.githubusercontent.com/50384819/206661427-5351bfbc-613c-4e36-b1e7-c64068e932ea.png)
![image](https://user-images.githubusercontent.com/50384819/206661898-b0a19b61-7cc1-4334-ae97-61dc87686503.png)

**Comment by tangketan** [comment]
It's a bug of small overhang detection. I'll fix it soon.

**Comment by tangketan** [comment]
This bug has been fixed. Please wait for our next version V1.7.

**Comment by SaltWei** [comment]
Please reopen if 1.7.4 doesn't fix
