### ISSUE TITLE
Stream 720p when set to 1080p in Bambu Studio

### ISSUE THREAD

**Issue by VACIndustries** [bambulab/BambuStudio#857]
**Describe the bug**

**To Reproduce**
1. Followed these instructions here https://wiki.bambulab.com/en/software/bambu-studio/virtual-camera
2. Selected 1080p in Bambu Studio Resolution under "Go Live"

**Expected behavior**
Stream in 1080p

**Screenshots**
1920x1080 OBS setup, but it does not populate without zooming/stretching:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3279061/208130384-87fd574f-6695-429e-9850-019d0a811e91.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/3279061/208130571-34f36e2d-5ff1-424d-ac8e-759ba0c7f0af.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.4

**Comment by Benderrodrigu3z** [comment]
you might have to also hit 1080p on the printers Screen, its under Tab 4 General

**Comment by VACIndustries** [comment]
Tried this...tried updating the firmware on the printer and restarting the printer and verifying the 1080p is selected on the printer's display as well -- still 720p resolution

**Comment by bambu123** [comment]
You have to restart the stream after switching the frame size of the printer.
OBS has also to be restarted because it may not respond to in-stream frame size changes.
Also, OBS is not telling the actual size of the stream.  You can use Video Lan to open the SDP file to see the size of the stream.
The size is really 1760 * 1080, not 1920 * 1080 for not showing outside of the printer.

**Comment by bambu123** [comment]
@VACIndustries Has the problem been solved?

**Comment by VACIndustries** [comment]
I think so. Will reopen if I find otherwise. Thanks for the recommendations

**Comment by bambu123** [comment]
Also, update OBS to 29.0.0 will respond to frame size changes.
