### ISSUE TITLE
Supports from separate bodies going into a body that's next to it

### ISSUE THREAD

**Issue by leofaoro** [bambulab/BambuStudio#981]
**Describe the bug**
Supports from 2 bodies close together are being built inside the other body. See screenshot of first layer

**3mf File for This Bug**
[bug.3mf.zip](https://github.com/bambulab/BambuStudio/files/10322355/bug.3mf.zip)

**To Reproduce**
place 2 bodies close to each other (does not need to touch), enable supports

**Expected behavior**
merging of supports without interfering with the slicing of the adjacent body

**Screenshots**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/1944817/210017074-f8fbff57-31f8-4e48-b645-0a7d118af219.png">
this is showing the first layer

**Desktop (please complete the following information):**
MacOS Ventura
Bambu Lab Studio 1.4.1.52

**Comment by MusangKingBambulab** [comment]
Hi, @leofaoro . I recommand to assemble these two objects together first (check 1st fig below) and then to generate support structure based on this single assembly (check 2nd fig below). If not, the support structure will be generated independently and overlaped just like what you have shown.

![image](https://user-images.githubusercontent.com/116701250/210169273-06726053-1b90-467a-afa1-71dd4185e5dc.png)

![image](https://user-images.githubusercontent.com/116701250/210169384-e6ad7a8b-e55a-4ba7-891d-fd71b8ce56c6.png)

Since this is not the bug of this release. Please allow me to close this issue. Happy new year!

**Comment by leofaoro** [comment]
Fantastic thank you. I didn't know about the assembly part.
